/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FileRouteImport } from './routes/file'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PageIdIndexRouteImport } from './routes/$pageId/index'

const FileRoute = FileRouteImport.update({
  id: '/file',
  path: '/file',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PageIdIndexRoute = PageIdIndexRouteImport.update({
  id: '/$pageId/',
  path: '/$pageId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/file': typeof FileRoute
  '/$pageId': typeof PageIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/file': typeof FileRoute
  '/$pageId': typeof PageIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/file': typeof FileRoute
  '/$pageId/': typeof PageIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/file' | '/$pageId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/file' | '/$pageId'
  id: '__root__' | '/' | '/file' | '/$pageId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FileRoute: typeof FileRoute
  PageIdIndexRoute: typeof PageIdIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/file': {
      id: '/file'
      path: '/file'
      fullPath: '/file'
      preLoaderRoute: typeof FileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$pageId/': {
      id: '/$pageId/'
      path: '/$pageId'
      fullPath: '/$pageId'
      preLoaderRoute: typeof PageIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FileRoute: FileRoute,
  PageIdIndexRoute: PageIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
